Limit the maximum number of search vectors to generate per index (#10284)
This fixes a crash when multiple thousand values are to be indexed due to PostgreSQL rejecting the statement. Such crash would look like this:
```
django.db.utils.OperationalError: stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
```